In [25]:
import torch
import math

# Tensors

Following along with the PyTorch beginner Youtube playlist.

## Basic Tensor Creation

We can setup an empty tensor with 2 rows and three cols.

In [26]:
x = torch.empty(2,3)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[1.9361e+02, 4.5712e-41, 8.9200e-38],
        [3.0928e-41, 4.4842e-44, 0.0000e+00]])


PyTorch also provides other initialization methods like zeros, ones, and rand.

In [27]:
zeros = torch.zeros(2,3)
print(zeros)

ones = torch.ones(2,3)
print(ones)

torch.manual_seed(42)
random = torch.rand(2,3)
print(random)

random2 = torch.rand(2,3)
print(random2)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


In [28]:
result = (ones * 3) + ones
print(result)
print(result.shape)
print(len(result.shape))

tensor([[4., 4., 4.],
        [4., 4., 4.]])
torch.Size([2, 3])
2


The *_like methods provide a way to create a tensor with the same shape as the provided tensor.

In [30]:
x = torch.empty(2,3)
print(x.shape)
print(x)

# the *_like methods produce tensors w/ the same shape as the provided tensor.
y = torch.empty_like(x)
print(y.shape)
print(y)

z = torch.zeros_like(x)
print(z.shape)
print(z)

random_like = torch.rand_like(x)
print(random_like.shape)
print(random_like)

torch.Size([2, 3])
tensor([[1.0121e-37, 3.0928e-41, 1.9361e+02],
        [4.5712e-41, 4.4842e-44, 0.0000e+00]])
torch.Size([2, 3])
tensor([[1.9361e+02, 4.5712e-41, 8.9073e-38],
        [3.0928e-41, 0.0000e+00, 0.0000e+00]])
torch.Size([2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])
tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])


We can also create tensors from regular collections.

In [31]:
from_collection = torch.tensor([[1.0, 1.0], [2.0, 2.0]])
print(from_collection.shape)
print(from_collection)

torch.Size([2, 2])
tensor([[1., 1.],
        [2., 2.]])


## Data Types

Tensors can have different data types, the default being float32. The full list being:

- bool
- int8
- uint8
- int16
- int32
- int64
- half
- float
- double
- bfloat

In [33]:
a = torch.ones((2,3), dtype=torch.int16)
print(a)

b = torch.rand((2,3), dtype=torch.float64)
print(b)

c = b.to(torch.int32)
print(c)

default = torch.zeros(2,3)
print(default.dtype)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[0.6234, 0.4373, 0.0747],
        [0.6834, 0.3122, 0.3091]], dtype=torch.float64)
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
torch.float32


## Math & Logic

Basic arithmetic and scalar operations.

In [34]:
ones = torch.ones(2,3)
twos = torch.ones(2,3) * 2
fours = twos ** 2
sqrts = twos ** 0.5

print(ones)
print(twos)
print(fours)
print(sqrts)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[4., 4., 4.],
        [4., 4., 4.]])
tensor([[1.4142, 1.4142, 1.4142],
        [1.4142, 1.4142, 1.4142]])


Tensors must be the same shape for operations to work. The multiplication below will result in an error.

In [37]:
a = torch.rand(2,3)
b = torch.rand(3,2)
a * b

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

## Tensor Broadcasting

In general tensors need to be the same shape for operations to work, however there is an exception. In the case below the 1x4 tensor is multiplied by both columns of rand. Broadcasting will occur when tensors have similarities in their shape.

In [36]:
rand = torch.rand(2,4)
double = rand * (torch.ones(1,4) * 2)
print(rand)
print(double)

tensor([[0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071]])
tensor([[1.5078, 0.3905, 0.0101, 0.6136],
        [0.2330, 1.8205, 1.2880, 1.4142]])


### Broadcasting Rules

- Each tensor must have one dimension (no empty tensors)
- Comparing the dimension sizes of the two tensors, going from last to first:
  - Each dimension must be equal or
  - One of the dimensions must be of size 1 or
  - The dimension does not exist in one of the tensors


## Common Tensor Operations


In [41]:
r = torch.rand(3,3) * 2 - 1

print(torch.abs(r))
print(torch.ceil(r))
print(torch.floor(r))
print(torch.clamp(r, -0.5, 0.5))

tensor([[0.5720, 0.7770, 0.5046],
        [0.3049, 0.2114, 0.2550],
        [0.5961, 0.6798, 0.7252]])
tensor([[1., -0., -0.],
        [1., 1., -0.],
        [1., 1., -0.]])
tensor([[ 0., -1., -1.],
        [ 0.,  0., -1.],
        [ 0.,  0., -1.]])
tensor([[ 0.5000, -0.5000, -0.5000],
        [ 0.3049,  0.2114, -0.2550],
        [ 0.5000,  0.5000, -0.5000]])


In [44]:
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print("Sine and arcsine")
print(angles)
print(sines)
print(inverses)

Sine and arcsine
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [45]:
b = torch.tensor([1,5,11])
c = torch.tensor([2,7,10])
print(torch.bitwise_xor(b,c))

tensor([3, 2, 1])


In [47]:
d = torch.tensor([[1.,2.], [3., 4.]])
e = torch.ones(1,2)
print(d)
print(e)
print(torch.eq(d,e))

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 1.]])
tensor([[ True, False],
        [False, False]])


In [50]:
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1,2,1,2,1,2])))

tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [58]:
v1 = torch.tensor([1.,0.,0.])
v2 = torch.tensor([0.,1.,0.])

m1 = torch.rand(2,2)
m2 = torch.tensor([[3., 0.], [0., 3.]])

print(torch.cross(v1, v2))
print(m1)
# torch.mm, torch.malmul, and torch.mul all have differect matrix ops wrt to broadcasting and element-wise ops. Could be confusing.
m3 = torch.matmul(m1, m2)
print(m3)
print(torch.svd(m3))

tensor([0., 0., 1.])
tensor([[0.2007, 0.5014],
        [0.3139, 0.4654]])
tensor([[0.6020, 1.5042],
        [0.9418, 1.3961]])
torch.return_types.svd(
U=tensor([[-0.6930, -0.7210],
        [-0.7210,  0.6930]]),
S=tensor([2.3237, 0.2480]),
V=tensor([[-0.4718,  0.8817],
        [-0.8817, -0.4718]]))


## In Place Operations

Most tensor operations have versions with an underscore suffix. e.g. tensor.sin_(x). These operations will modify the input tensor in-place instead of creating a new output tensor.

In [65]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print(f"Original: {a}")
print(f"sin     : {torch.sin(a)}")
print(f"Original: {a}")

print(f"in-place: {torch.sin_(a)}")
print(f"Original: {a}")

Original: tensor([0.0000, 0.7854, 1.5708, 2.3562])
sin     : tensor([0.0000, 0.7071, 1.0000, 0.7071])
Original: tensor([0.0000, 0.7854, 1.5708, 2.3562])
in-place: tensor([0.0000, 0.7071, 1.0000, 0.7071])
Original: tensor([0.0000, 0.7071, 1.0000, 0.7071])


We can use the 'out' parameter to output data without (necessarily) allocating extra memory if we've already got it around.

In [70]:
a = torch.rand(2,2)
b = torch.rand(2,2)
c = torch.zeros(2,2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
assert c is d
assert id(c), old_id

torch.rand(2,2, out=c)
print(c)
assert id(c), old_id

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.4250, 0.2709],
        [0.9295, 0.6115]])


## Copying Tensors

Assigning a tensor to a variable makes the variable a _label_ of the the tensor. It does not copy the tensor.

In [66]:
a = torch.ones(2,2)
b = a
a[0][1] = 2
print(b[0][1])

tensor(2.)


If we do want to copy the tensor, we have the clone() method. Important to note, autograd enable/disable state IS copied with clone()

In [72]:
a = torch.ones(2,2)
b = a.clone()
assert b is not a
print(torch.eq(a,b))
a[0][1] = 42
print(a)
print(b)

tensor([[True, True],
        [True, True]])
tensor([[ 1., 42.],
        [ 1.,  1.]])
tensor([[1., 1.],
        [1., 1.]])


## Moving to GPU

By default tensor operations aren't computed on the GPU.

In [73]:
if torch.cuda.is_available():
    print("GPU WOOOOOO!")
else:
    print("Sad :(")

GPU WOOOOOO!


Once we know a GPU device exists, we can allocate the tensor into the GPU's memory.

In [75]:
if torch.cuda.is_available():
    gpu = torch.rand(2,2, device="cuda")
    print(gpu)
else:
    print("sad")

tensor([[0.9877, 0.1289],
        [0.5621, 0.5221]], device='cuda:0')


In [81]:
print(torch.cuda.device_count())
# If we had more than 1, can specify with index e.g. torch.device('cuda:1')

1


In [80]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

y = torch.rand(2,2)
y = y.to(device)
print(y)

tensor([[0.6783, 0.8870],
        [0.0293, 0.6161]], device='cuda:0')


## Manipulating Tensor Shapes

Sometimes tensor shapes need to change. Let's say we trained a model using tensors of N x 3 X 226 x 226 where N is the batch size. How do we do inference if we have one image as a 3 X 226 X 226 tensor?

In [83]:
a = torch.rand(3,226,226)
b = a.unsqueeze(0)
print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


We can see that `unsqueeze(0)` added an extra 0th dimension!

In [88]:
a = torch.rand(1,20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2,2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.4300, 0.2789, 0.1550, 0.3292, 0.1149, 0.4141, 0.5295, 0.9095, 0.4063,
         0.2977, 0.5557, 0.9447, 0.6380, 0.5311, 0.3390, 0.2882, 0.5134, 0.1086,
         0.2092, 0.8087]])
torch.Size([20])
tensor([0.4300, 0.2789, 0.1550, 0.3292, 0.1149, 0.4141, 0.5295, 0.9095, 0.4063,
        0.2977, 0.5557, 0.9447, 0.6380, 0.5311, 0.3390, 0.2882, 0.5134, 0.1086,
        0.2092, 0.8087])
torch.Size([2, 2])
torch.Size([2, 2])


We may only squeeze dimensions of extent 1.

In [89]:
a = torch.ones(4,3,2)
b = torch.rand(  3)
c = b.unsqueeze(1)
print(c.shape)
print(a * c)

torch.Size([3, 1])
tensor([[[0.7837, 0.7837],
         [0.5438, 0.5438],
         [0.3064, 0.3064]],

        [[0.7837, 0.7837],
         [0.5438, 0.5438],
         [0.3064, 0.3064]],

        [[0.7837, 0.7837],
         [0.5438, 0.5438],
         [0.3064, 0.3064]],

        [[0.7837, 0.7837],
         [0.5438, 0.5438],
         [0.3064, 0.3064]]])


Sometimes we need more shape change than (un)sequeeze can provide. In those cases we have `reshape()`.

In [94]:
output3d = torch.rand(6,20,20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

torch.Size([6, 20, 20])
torch.Size([2400])


## Numpy Bridge

In [95]:
import numpy as np

nparr = np.ones((2,3))
print(nparr)

tensor = torch.from_numpy(nparr)
print(tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [101]:
ptrand = torch.rand(2,2)
print(ptrand)

nprand = ptrand.numpy()
print(nprand)

# changes are reflected because they use the same underlying memory

ptrand[0][0] = 42
print(ptrand[0][0])
print(nprand[0][0])

nprand[0][0] = 101
print(ptrand[0][0])
print(nprand[0][0])

tensor([[0.8862, 0.6215],
        [0.0780, 0.0986]])
[[0.8861934  0.62153304]
 [0.07804674 0.09863693]]
tensor(42.)
42.0
tensor(101.)
101.0
